config/routes.rb
Rails.application.routes.draw do
  resources :pets

  get 'proposals/create'

  get 'acceptances/create'

  get 'proposals/show'

  post "/acceptances" => "acceptances#create"
  post "/jobs" => "jobs#create"

  get '/owners/:id/show' => 'owners#show'
  post '/proposals' => 'proposals#create'
  post '/remove/:id' => "pets#remove"

  get '/clear' => 'owners#clear'
  get '/login' => 'owners#login'
  post '/owners/login' => 'owners#log'
  post '/sitters/login' => 'sitters#log'
  delete '/sitters' =>'sitters#logout'
  delete '/owners' =>'owners#logout'
  get "/owners/:id/edit" => "owners#edit"

  post "/sitterscreate" => "sitters#create"

  get "sitters/:id/edit" => "sitters#edit"
  root 'owners#index'
  get "owners/oldjobs" => "owners#oldjobs"
  get "sitters/oldjobs" => "sitters#oldjobs"
  post '/owners'=>'owners#create'
  get '/profile/mypets' => 'owners#mypets'
  get "sitters/:id" => "sitters#show"
  patch "sitters/:id" => "sitters#update"
  delete "sitters/:id" => "sitters#destroy"

  patch "owners/:id" => "owners#update"

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :owner
  belongs_to :animal
  has_many :watches
  mount_uploader :image, ImageUploader
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.where(:owner_id => session[:id])
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @owner=Owner.find(session[:id])
  end
  def remove
    pet=Pet.find(params[:id]).destroy
    redirect_to :back
  end
  # GET /pets/new
  def new
    @pet = Pet.new
    @animals=Animal.all
  end

  # GET /pets/1/edit
  def edit
    @animals=Animal.all
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to "/pets", notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:owner_id, :name, :age, :animal_id, :image)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input type="hidden" name="pet[owner_id]" value="<%=session[:id]%>">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="select">
   Animal<select name = "pet[animal_id]">
     <% @animals.each do |a| %>
       <option value = "<%= a.id %>"><%=a.kind %></option>
     <% end %>
 </div>
  <div class="field" >
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Pet', :class => 'cr_pet'%>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<<<<<<< HEAD
<link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
<h1 id='newfont'>My Pets</h1>

<h1>My pets</h1>


<table>
<col width="150">
<col width="150">
<col width="80">
<col width="80">

  <thead>
    <tr>
      <th>Picture</th>
      <th>Name</th>
      <th>Age</th>
      <th>Animal</th>
      <th>Actions</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= image_tag pet.image_url(:thumb) if pet.image? %></td>
        <td><%= pet.name %></td>
        <td><%= pet.age %></td>
        <td><%= pet.animal.kind %></td>
        <td><%= link_to 'Show', pet %>
        <%= link_to 'Edit', edit_pet_path(pet) %></td>
       <td><form method="post" action="/pets/<%= pet.id %>"><input type='hidden' name ='authenticity_token' value="<%=form_authenticity_token%>"><input type='hidden' name='_method' value='delete'><input type="submit" value="Delete"></form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Pet', new_pet_path %>

<%= link_to 'Add Pet', new_pet_path %>

app/views/pets/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
<div id="add_new_pet">
<h1 id='newfont'>Add a new pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

</div>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @pet.image_url(:thumb) if @pet.image? %>
</p>


<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @pet.animal.kind %>
</p>